### ISSUE TITLE
Host Cascadia Code on a CDN

### ISSUE THREAD

**Issue by RehanSaeed** [microsoft/cascadia-code#246]
# Description of the new feature/enhancement (with images if possible)

I'd like a CDN URL where I can get the latest version of the fonts, as well specific versions.

# Proposed technical implementation details (optional)

Automate the release to a CDN.

**Comment by RehanSaeed** [comment]
This will also require you to write a short CSS file with the `font-face` properties setup in it.

**Comment by lipis** [comment]
Is this happening?

**Comment by JeepNL** [comment]
🎤 :)

**Comment by christoph-jeanluc-schneider** [comment]
i would be interested in this 🙋‍♂️

**Comment by franckrasolo** [comment]
It's available at https://www.cdnfonts.com/cascadia-code.font and I configure it as follows:

```css
@font-face {
  font-family: 'Cascadia Code';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Cascadia Code'), url(https://fonts.cdnfonts.com/s/29131/Cascadia.woff) format('woff');
}
```
